config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs

  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    if @doc.destroy
      redirect_to docs_path
    end
  end

  private

    def doc_params
      params.require(:doc).permit(:name, :body)
    end

    def find_doc
      @doc = Doc.find(params[:id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
<%= f.input :name %>
<%= f.input :body %>
<%= f.button :submit %>
<% end %>

app/views/docs/edit.html.erb
<h2> Edit your doc</h2>
<%= render 'form' %>
<%= link_to 'Cancel', docs_path %>

app/views/docs/index.html.erb
<% @docs.each do |doc| %>
<h2><%= link_to doc.name, doc %></h2>
<p><%= time_ago_in_words(doc.created_at) %></p>
<%= truncate(doc.body, length:50) %>
<%end%>
<p><%= link_to 'Create new doc', new_doc_path %> </p>

app/views/docs/new.html.erb
<h2>Hello create a doc</h2>
<%= render 'form' %>

app/views/docs/show.html.erb
<h1><%= @doc.name %></h1>
<p><%= @doc.body %></p>
<%= link_to 'Edit', edit_doc_path(@doc) %>
<%= link_to 'Delete', doc_path(@doc), method: :delete, data: { confirm: "Are you sure?"} %>
<%= link_to 'Back', docs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>